volumes:
  cache:
    driver: local

networks:
  elastic:
    driver: bridge

services:
  postgresql:
    image: postgres
    restart: always
    container_name: test-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  redis:
    image: redis:latest
    restart: always
    container_name: test-redis
    ports:
      - '6379:6379'
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${PASSWORD}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${PASSWORD}
    volumes:
      - cache:/data
  elasticsearch:
    image: elasticsearch:8.8.0
    restart: always
    container_name: test-elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - elastic
  app:
    build:
      context: .
    container_name: test-service
    depends_on:
      - postgresql
      - redis
      - elasticsearch
    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}