volumes:
  cache:
    driver: local

networks:
  backend:
    driver: bridge

services:
  postgresql:
    image: postgres
    restart: always
    container_name: test-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    networks:
      - backend
  redis:
    image: redis:latest
    restart: always
    container_name: test-redis
    ports:
      - '6379:6379'
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${PASSWORD}
    volumes:
      - cache:/data
    networks:
      - backend
    command: redis-server --save 20 1 --loglevel warning --requirepass ${PASSWORD}
  elasticsearch:
    image: elasticsearch:8.8.0
    restart: always
    container_name: test-elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - backend
  logstash:
    image: logstash:8.8.0
    restart: always
    container_name: test-logstash
    depends_on:
      elasticsearch:
        condition: "service_started"
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./src/main/resources/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    networks:
      - backend
    command: logstash -f /etc/logstash/conf.d/logstash.conf
  kibana:
    image: kibana:8.8.0
    restart: always
    container_name: test-kibana
    depends_on:
      elasticsearch:
        condition: "service_started"
    ports:
      - "5601:5601"
    networks:
      - backend
  app:
    build:
      context: .
    container_name: test-service
    depends_on:
      - postgresql
      - redis
      - elasticsearch
      - logstash
      - kibana
    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    networks:
      - backend