spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      enable-statistics: true
      time-to-live: 2500ms
  datasource:
    username: ${DB_USERNAME}
    password: ${PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      password: ${PASSWORD}
      ssl:
        enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8080
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always