spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      enable-statistics: true
      time-to-live: 2500ms
  datasource:
    username: ${DB_USERNAME}
    password: ${PASSWORD}
    name: ${DB_NAME}
    url: jdbc:postgresql://postgresql:5432
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      password: ${PASSWORD}
      ssl:
        enabled: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  boot:
    admin:
      client:
        url: http://localhost:8080
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always